### ISSUE TITLE
Vytvoreni prostredi na windows

### ISSUE THREAD

**Issue by waldibro** [tomasbedrich/skoleni-python#11]
Ahoj, 
Poznamky k vytvareni noveho prostredi na windows 7 (64b) - python v 3.7 - pred skolenim (8/10/18)

1. python3 vs python
Po instalaci windows balicku nefunguje prikaz (python3 je neznamy prikaz)
`python3 -m venv venv`
Nasledujici prikaz funguje
`python -m venv venv`

2. instalace zavislosti
Vykonavani prikazu 
`pip3 install -r requirements.txt`
skoncilo s chybou
`Collecting widgetsnbextension==3.1.4 (from -r requirements.txt (line 50))
  Downloading https://files.pythonhosted.org/packages/fa/ce/f6442355d348f392975ccc2fa50910706913355b8ce72ae3256f7dc0d17e/widgetsnbextension-3.1.4-py2.py3-none-any.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 2.2MB/s
Requirement already satisfied: setuptools>=18.5 in c:\vb\skoleni-python-master\venv\lib\site-packages (from ipython==6.2.1->-r requirements.txt (line 12)) (39.0.1)
Collecting colorama; sys_platform == "win32" (from ipython==6.2.1->-r requirements.txt (line 12))
Collecting pywinpty>=0.5; os_name == "nt" (from terminado==0.8.1->-r requirements.txt (line 43))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    colorama; sys_platform == "win32" from https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl#sha256=463f8483208e921368c9f306094eb6f725c6ca42b0f97e313cb5d5512459feda (from ipython==6.2.1->-r requirements.txt (line 12))
    pywinpty>=0.5; os_name == "nt" from https://files.pythonhosted.org/packages/29/6c/c207ba85325e7d3fa5df3e2b51954705bb378de54065ee01ba89317c790d/pywinpty-0.5.4.tar.gz#sha256=4ee8
193b19d77ab59097a000a2c52b36e768e92263812e0c0b40306be8927fb4 (from terminado==0.8.1->-r requirements.txt (line 43))`

3. spusteni Jupytera
Pravdepodobne v navaznosti na predchozi chybu pri isntalaci zavislosti, pred spustenim jupytera
`jupyter notebook`
bylo zapotrebi nainstalovat jupyter pomoci
`pip install jupyter`

w.

**Comment by tomasbedrich** [comment]
Closed by 97fc425d64d3dedf141c12ca5deca3661b1eea52
